require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompanyGuidesController do

  # This should return the minimal set of attributes required to create a valid
  # CompanyGuide. As you add validations to CompanyGuide, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "company_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompanyGuidesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all company_guides as @company_guides" do
      company_guide = CompanyGuide.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:company_guides)).to eq([company_guide])
    end
  end

  describe "GET show" do
    it "assigns the requested company_guide as @company_guide" do
      company_guide = CompanyGuide.create! valid_attributes
      get :show, {:id => company_guide.to_param}, valid_session
      expect(assigns(:company_guide)).to eq(company_guide)
    end
  end

  describe "GET new" do
    it "assigns a new company_guide as @company_guide" do
      get :new, {}, valid_session
      expect(assigns(:company_guide)).to be_a_new(CompanyGuide)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_guide as @company_guide" do
      company_guide = CompanyGuide.create! valid_attributes
      get :edit, {:id => company_guide.to_param}, valid_session
      expect(assigns(:company_guide)).to eq(company_guide)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompanyGuide" do
        expect {
          post :create, {:company_guide => valid_attributes}, valid_session
        }.to change(CompanyGuide, :count).by(1)
      end

      it "assigns a newly created company_guide as @company_guide" do
        post :create, {:company_guide => valid_attributes}, valid_session
        expect(assigns(:company_guide)).to be_a(CompanyGuide)
        expect(assigns(:company_guide)).to be_persisted
      end

      it "redirects to the created company_guide" do
        post :create, {:company_guide => valid_attributes}, valid_session
        expect(response).to redirect_to(CompanyGuide.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_guide as @company_guide" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CompanyGuide).to receive(:save).and_return(false)
        post :create, {:company_guide => { "company_id" => "invalid value" }}, valid_session
        expect(assigns(:company_guide)).to be_a_new(CompanyGuide)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CompanyGuide).to receive(:save).and_return(false)
        post :create, {:company_guide => { "company_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_guide" do
        company_guide = CompanyGuide.create! valid_attributes
        # Assuming there are no other company_guides in the database, this
        # specifies that the CompanyGuide created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(CompanyGuide).to receive(:update).with({ "company_id" => "1" })
        put :update, {:id => company_guide.to_param, :company_guide => { "company_id" => "1" }}, valid_session
      end

      it "assigns the requested company_guide as @company_guide" do
        company_guide = CompanyGuide.create! valid_attributes
        put :update, {:id => company_guide.to_param, :company_guide => valid_attributes}, valid_session
        expect(assigns(:company_guide)).to eq(company_guide)
      end

      it "redirects to the company_guide" do
        company_guide = CompanyGuide.create! valid_attributes
        put :update, {:id => company_guide.to_param, :company_guide => valid_attributes}, valid_session
        expect(response).to redirect_to(company_guide)
      end
    end

    describe "with invalid params" do
      it "assigns the company_guide as @company_guide" do
        company_guide = CompanyGuide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CompanyGuide).to receive(:save).and_return(false)
        put :update, {:id => company_guide.to_param, :company_guide => { "company_id" => "invalid value" }}, valid_session
        expect(assigns(:company_guide)).to eq(company_guide)
      end

      it "re-renders the 'edit' template" do
        company_guide = CompanyGuide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CompanyGuide).to receive(:save).and_return(false)
        put :update, {:id => company_guide.to_param, :company_guide => { "company_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_guide" do
      company_guide = CompanyGuide.create! valid_attributes
      expect {
        delete :destroy, {:id => company_guide.to_param}, valid_session
      }.to change(CompanyGuide, :count).by(-1)
    end

    it "redirects to the company_guides list" do
      company_guide = CompanyGuide.create! valid_attributes
      delete :destroy, {:id => company_guide.to_param}, valid_session
      expect(response).to redirect_to(company_guides_url)
    end
  end

end
